export default {
  common: {
    delete: 'Delete',
    open: 'Open',
    create: 'Create',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    detail: 'Detail',
    share: 'Share',
    send: 'Send',
    skip: 'Skip',
    back: 'Back',
    notAssigned: 'Not assigned',
    lastUpdates: 'Last updated',
    clearAll: 'Clear all',
    or: 'or',
    code: 'Code',
    help: 'Help',
    settings: 'Settings',
    createIssue: 'Create issue',
    noResults: 'No results',
    summary: 'Summary',
    title: 'Title',
    description: 'Description',
    giveReview: 'Give review',
    addTitle: 'Add title',
    changeTitle: 'Change title',
    activity: 'Activity',
    addComment: 'Add comment...',
    advice: 'Advice',
    press: 'press',
    toAddComment: 'to add comment',
    edited: 'Edited',
    edit: 'Edit',
    created: 'Created',
    updateDate: 'Update date',
    thereNoAnything: "There's no anything",
    search: 'Search',
  },

  post: {
    posts: 'posts | post | posts',
  },

  user: {
    displayName: 'Name and surname',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    profile: 'Profile',
    displayNameUsernameOrEmail: 'Their name, surname, username or email',
    max10Users: 'You can invite no more than 10 users at a time.',
    followers: 'followers | follower | followers',
    followings: 'following | following | followings',
  },

  auth: {
    register: 'Register',
    registerAccount: 'Sign up to see photos and videos from your friends.',
    resetPassword: 'Reset password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    scanQrCode: 'Scan the QR code using the Google Authenticator app and enter the code in the field below',
    enter2FaCode: 'Enter the code from the Google Authenticator app',
    incorrect2FaCode: 'Invalid code, try again',
    recoverPassword: 'Recover the password from the Jira account',
    sendEmail: 'Send Email',
    passwordsNotMatch: 'Passwords not match',
  },

  validation: {
    required: 'Required field',
    incorrectEmailFormat: 'Incorrect Email format',
    usernameTaken: 'Username already taken',
    emailTaken: 'Such email already taken',
    minChars: 'Минимум 0 символов | Минимум {n} символ | Минимум {n} символа | Минимум {n} символов',
    maxChars: 'Максимум 0 символов | Максимум {n} символ | Максимум {n} символа | Максимум {n} символов',
    upToChars: 'До 0 символов | До {n} символа | До {n} символов | До {n} символов',
  },

  tabs: {
    work: 'Work',
    projects: 'Projects',
    filters: 'Filters',
    dashboards: 'Dashboards',
    people: 'People',
    apps: 'Apps',
  },

  notification: {
    notifications: 'Notifications',
    showUnread: 'Show only unread',

    noLast30Days: 'No notifications for the last 30 days',
    noUnreadLast30Days: 'All notifications for the last 30 days have been read',

    markRead: 'Mark as read',
    markAllRead: 'Mark all as read',
    markUnread: 'Mark as unread',

    typeTitles: {
      likedPhoto: 'liked your photo',
      likedVideo: 'liked your video',
      likedComment: 'liked your comment',
      followed: 'started following you',
    },
  },

  date: {
    secondsAgo: '0 seconds ago | {n} second ago | {n} seconds ago',
    minutesAgo: '0 minutes ago | {n} minute ago | {n} minutes ago',
    hoursAgo: '0 hours ago | {n} hour ago | {n} hours ago',
    daysAgo: '0 days ago| {n} day ago | {n} days ago',
    monthsAgo: '0 months ago | {n} month ago | {n} months ago',

    today: 'Today',
    yesterday: 'Yesterday',
    older: 'Older',
  },

  table: {
    name: 'Name',
    key: 'Key',
    type: 'Type',
    template: 'Template',
    leader: 'Leader',
    group: 'Group',
    owner: 'Owner',
    resetFilters: 'Reset filters',
  },
};
