export default {
  common: {
    delete: 'Delete',
    open: 'Open',
    create: 'Create',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    detail: 'Detail',
    share: 'Share',
    send: 'Send',
    skip: 'Skip',
    back: 'Back',
    notAssigned: 'Not assigned',
    lastUpdates: 'Last updated',
    clearAll: 'Clear all',
    or: 'or',
    code: 'Code',
    help: 'Help',
    settings: 'Settings',
    createIssue: 'Create issue',
    noResults: 'No results',
    summary: 'Summary',
    title: 'Title',
    description: 'Description',
    giveReview: 'Give review',
    addTitle: 'Add title',
    changeTitle: 'Change title',
    activity: 'Activity',
    addComment: 'Add comment...',
    advice: 'Advice',
    press: 'press',
    toAddComment: 'to add comment',
    edited: 'Edited',
    edit: 'Edit',
    created: 'Created',
    updateDate: 'Update date',
    thereNoAnything: "There's no anything",
    search: 'Search',
  },

  user: {
    displayName: 'Display name',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    profile: 'Profile',
    displayNameUsernameOrEmail: 'Their display name, username or email',
    max10Users: 'You can invite no more than 10 users at a time.',
  },

  auth: {
    register: 'Register',
    registerJiraAccount: 'Create new Jira account',
    resetPassword: 'Reset password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signInJira: 'Sign in Jira',
    scanQrCode: 'Scan the QR code using the Google Authenticator app and enter the code in the field below',
    enter2FaCode: 'Enter the code from the Google Authenticator app',
    incorrect2FaCode: 'Invalid code, try again',
    recoverPassword: 'Recover the password from the Jira account',
    sendEmail: 'Send Email',
    passwordsNotMatch: 'Passwords not match',
  },

  validation: {
    required: 'Required field',
    incorrectEmailFormat: 'Incorrect Email format',
    usernameTaken: 'Username already taken',
    emailTaken: 'Such email already taken',
    minChars: 'Минимум 0 символов | Минимум {n} символ | Минимум {n} символа | Минимум {n} символов',
    maxChars: 'Максимум 0 символов | Максимум {n} символ | Максимум {n} символа | Максимум {n} символов',
    upToChars: 'До 0 символов | До {n} символа | До {n} символов | До {n} символов',
  },

  tabs: {
    work: 'Work',
    projects: 'Projects',
    filters: 'Filters',
    dashboards: 'Dashboards',
    people: 'People',
    apps: 'Apps',
  },

  notification: {
    notifications: 'Notifications',
    showUnread: 'Show only unread',

    noLast30Days: 'No notifications for the last 30 days',
    noUnreadLast30Days: 'All notifications for the last 30 days have been read',

    markRead: 'Mark as read',
    markAllRead: 'Mark all as read',
    markUnread: 'Mark as unread',

    typeTitles: {
      news: 'News on the Jira app',
      issueAssign: 'You have been assigned a task',
      issueWatchUpdate: 'The observed task has been updated',
    },
  },

  date: {
    secondsAgo: '0 секунд назад | {n} секунду назад | {n} секунды назад | {n} секунд назад',
    minutesAgo: '0 минут назад | {n} минуту назад | {n} минуты назад | {n} минут назад',
    hoursAgo: '0 час назад | {n} час назад | {n} часа назад | {n} часов назад',
    daysAgo: '0 день назад| {n} день назад | {n} дня назад | {n} дней назад',
    monthsAgo: '0 месяц назад | {n} месяц назад | {n} месяца назад | {n} месяцев назад',

    today: 'Today',
    yesterday: 'Yesterday',
    older: 'Older',
  },

  table: {
    name: 'Name',
    key: 'Key',
    type: 'Type',
    template: 'Template',
    leader: 'Leader',
    group: 'Group',
    owner: 'Owner',
    resetFilters: 'Reset filters',
  },
};
